# Generated by Django 4.2.1 on 2023-06-01 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='profile_pics')),
                ('learning_level', models.FloatField(default=1.0)),
                ('rating', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('learning_word', models.CharField(default='')),
                ('repeating_word', models.CharField(default='')),
                ('mode', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgetting_coef', models.FloatField(default=1.0)),
                ('last_repeating', models.DateTimeField()),
                ('learning_date', models.DateTimeField()),
                ('repeating', models.IntegerField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.engrusdict')),
            ],
            options={
                'verbose_name': 'LearnedWord',
                'verbose_name_plural': 'LearnedWords',
            },
        ),
    ]
