# Generated by Django 4.2.1 on 2023-05-08 17:00
import json

import django.contrib.postgres.fields.hstore
from django.db import migrations


def makeInit(apps, schema_editor):
    profiles = apps.get_model('users', 'Profile')
    profiles.objects.create(image="default.jpeg", learning_level=1.0, learned_words=json.dumps(
        {"hello": {"forgeting_coef": 1.0, "last_repeating": '08.05.2023 20:47', 'repeating': 1}}), user_id=1)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(makeInit)
    ]
