# Generated by Django 4.2.1 on 2023-05-08 17:00

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learned_words',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}),
        ),
    ]
