# Generated by Django 4.2.1 on 2023-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_learned_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learned_words',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
