# Generated by Django 4.2.1 on 2023-05-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20230508_1603'),
        ('users', '0004_alter_profile_learned_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fogetting_coef', models.FloatField(default=1.0)),
                ('last_repeating', models.DateTimeField()),
                ('repeating', models.IntegerField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.engrusdict')),
            ],
            options={
                'verbose_name': 'LearnedWord',
                'verbose_name_plural': 'LearnedWords',
            },
        ),
    ]
