# Generated by Django 4.2.1 on 2023-05-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_learnedwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnedwords',
            old_name='fogetting_coef',
            new_name='forgetting_coef',
        ),
    ]
