# Generated by Django 4.2.1 on 2023-05-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_fogetting_coef_learnedwords_forgetting_coef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learned_words',
        ),
    ]
