# Generated by Django 4.2.1 on 2023-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngRusDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(verbose_name='rus')),
                ('eng', models.CharField(verbose_name='eng')),
                ('complexity', models.FloatField(default=1)),
            ],
        ),
    ]
