# Generated by Django 4.2.1 on 2023-05-07 21:20
import os
from pathlib import Path

from django.db import migrations

from djangoProject3.settings import BASE_DIR


def add_words(apps, schema_editor):
    rus_eng_dict = apps.get_model('home', 'EngRusDict')

    words = open(os.path.join(BASE_DIR, '5000_words.txt'))
    for word in words.readlines():
        eng, rus = word.split(";")
        for wordru in rus.strip("\"")[:-2].split(","):
            rus_eng_dict.objects.create(rus=wordru.strip(), eng=eng.strip("\""))


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_words)
    ]
